snapshot_path = "db/snapshot.db"
log_path = "db/event-db.log"
database = "antdb"
table_data_path = "db/tables"
page_size_bytes = 8192
table_memory_limit_bytes = 67108864
auto_vacuum_interval_secs = 300